### PR TITLE
adjust release workflow

### PR DESCRIPTION
**Pull request by PaulRitter**
- the release will now only contain the .exe
- deleted the "Builded"-folder

### CODE REVIEW

**Comment by SlejmUr** [comment]
The problem is while checking the update it will automaticly grab the EXE from the Builded folder.

**Comment by PaulRitter** [comment]
good point, i missed that. Update will now grab the .exe from the latest release in the repo.

**Comment by SlejmUr** [comment]
Thx, I will push the update when I was home

**Comment by PaulRitter** [comment]
fyi, you dont need to manually create a release. all you need to do is tag a commit & push that tag, the workflow will do the rest

**Pull request merged**
